"""primer

Revision ID: 9ba3b6213988
Revises: 
Create Date: 2024-10-03 15:55:27.496651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba3b6213988'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listaschequeo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombrePermiso', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propiedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombrePropiedad', sa.String(length=45), nullable=True),
    sa.Column('tipo', sa.String(length=45), nullable=True),
    sa.Column('formato', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreProyecto', sa.String(length=45), nullable=True),
    sa.Column('tipoDeProyecto', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listasChequeo_has_propiedades',
    sa.Column('listasChequeo_id', sa.Integer(), nullable=False),
    sa.Column('propiedades_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listasChequeo_id'], ['listaschequeo.id'], ),
    sa.ForeignKeyConstraint(['propiedades_id'], ['propiedades.id'], ),
    sa.PrimaryKeyConstraint('listasChequeo_id', 'propiedades_id')
    )
    op.create_table('roles_has_permisos',
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.Column('permisos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permisos_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('roles_id', 'permisos_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=45), nullable=True),
    sa.Column('Correo', sa.String(length=45), nullable=True),
    sa.Column('Contrasena', sa.String(length=45), nullable=True),
    sa.Column('Documento', sa.String(length=45), nullable=True),
    sa.Column('tipoDocumento', sa.String(length=45), nullable=True),
    sa.Column('Apellido', sa.String(length=45), nullable=True),
    sa.Column('Direccion', sa.String(length=45), nullable=True),
    sa.Column('Telefono', sa.String(length=45), nullable=True),
    sa.Column('Usuario', sa.String(length=45), nullable=True),
    sa.Column('Sexo', sa.String(length=45), nullable=True),
    sa.Column('Fotografia', sa.String(length=45), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valor',
    sa.Column('idValor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Valor', sa.String(length=45), nullable=True),
    sa.Column('propiedades_id', sa.Integer(), nullable=False),
    sa.Column('listasChequeo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listasChequeo_id'], ['listaschequeo.id'], ),
    sa.ForeignKeyConstraint(['propiedades_id'], ['propiedades.id'], ),
    sa.PrimaryKeyConstraint('idValor')
    )
    op.create_table('administracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=45), nullable=True),
    sa.Column('dependencia', sa.String(length=45), nullable=True),
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=45), nullable=True),
    sa.Column('listado', sa.String(length=45), nullable=True),
    sa.Column('Profesíon', sa.String(length=45), nullable=True),
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('eslogan', sa.String(length=255), nullable=True),
    sa.Column('tipo_empresa', sa.String(length=100), nullable=False),
    sa.Column('nit', sa.Integer(), nullable=True),
    sa.Column('proyectos_id', sa.Integer(), nullable=True),
    sa.Column('usuarios_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyectos_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_has_usuarios',
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('roles_id', 'usuarios_id')
    )
    op.create_table('estudios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Institución', sa.String(length=45), nullable=True),
    sa.Column('Graduado', sa.Boolean(), nullable=True),
    sa.Column('Ano_de_grado', sa.String(length=45), nullable=True),
    sa.Column('Titulo', sa.String(length=45), nullable=True),
    sa.Column('Documento', sa.String(length=45), nullable=True),
    sa.Column('empleados_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empleados_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Empresa', sa.String(length=45), nullable=True),
    sa.Column('Fecha_inicio', sa.String(length=45), nullable=True),
    sa.Column('Fecha_final', sa.String(length=45), nullable=True),
    sa.Column('Cargo', sa.String(length=45), nullable=True),
    sa.Column('Jefe_inmediato', sa.String(length=45), nullable=True),
    sa.Column('Documento', sa.String(length=45), nullable=True),
    sa.Column('empleados_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empleados_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Fecha_factura', sa.String(length=45), nullable=True),
    sa.Column('Precio', sa.String(length=45), nullable=True),
    sa.Column('empleados_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empleados_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos_has_facturacion',
    sa.Column('proyectos_id', sa.Integer(), nullable=False),
    sa.Column('facturacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facturacion_id'], ['facturacion.id'], ),
    sa.ForeignKeyConstraint(['proyectos_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('proyectos_id', 'facturacion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyectos_has_facturacion')
    op.drop_table('facturacion')
    op.drop_table('experiencia')
    op.drop_table('estudios')
    op.drop_table('roles_has_usuarios')
    op.drop_table('empresa')
    op.drop_table('empleados')
    op.drop_table('administracion')
    op.drop_table('valor')
    op.drop_table('usuarios')
    op.drop_table('roles_has_permisos')
    op.drop_table('listasChequeo_has_propiedades')
    op.drop_table('roles')
    op.drop_table('proyectos')
    op.drop_table('propiedades')
    op.drop_table('permisos')
    op.drop_table('listaschequeo')
    # ### end Alembic commands ###
